# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/UnrealEngine/Linux_Unreal_Engine_5.4.0
GAMEPROJECTFILE =/home/pollutedmind/Projects/Gamedev/Campfires/CampfiresTest.uproject

TARGETS = \
	CampfiresTest-Linux-DebugGame  \
	CampfiresTest-Linux-Shipping  \
	CampfiresTest \
	CampfiresTestEditor-Linux-DebugGame  \
	CampfiresTestEditor-Linux-Shipping  \
	CampfiresTestEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend CampfiresTestEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug CampfiresTestEditor-Linux-Debug


CampfiresTest-Linux-DebugGame:
	 $(PROJECTBUILD) CampfiresTest Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CampfiresTest-Linux-Shipping:
	 $(PROJECTBUILD) CampfiresTest Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CampfiresTest:
	 $(PROJECTBUILD) CampfiresTest Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

CampfiresTestEditor-Linux-DebugGame:
	 $(PROJECTBUILD) CampfiresTestEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CampfiresTestEditor-Linux-Shipping:
	 $(PROJECTBUILD) CampfiresTestEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CampfiresTestEditor:
	 $(PROJECTBUILD) CampfiresTestEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
